# Generated by Django 4.0.3 on 2022-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('capacidade', models.FloatField()),
                ('ativo', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='regadores')),
                ('planta', models.ManyToManyField(blank=True, to='plantas.planta')),
            ],
            options={
                'verbose_name': 'Regador',
                'verbose_name_plural': 'Regadores',
            },
        ),
    ]
