# Generated by Django 4.0.3 on 2022-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regador',
            name='pressao_bar',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
