# Generated by Django 4.0.3 on 2022-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'O email cadastrado já existe.'}, max_length=50),
        ),
    ]
