# Generated by Django 4.0.3 on 2022-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('nome_cientifico', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=45)),
                ('reino', models.CharField(choices=[('B', 'briófitas'), ('A', 'angiospermas'), ('P', 'pteridófitas'), ('G', 'gimnospermas')], max_length=1)),
                ('iluminacao', models.TextField()),
                ('qtd_agua_dia', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
    ]
