# Generated by Django 4.0.3 on 2022-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='reino',
            new_name='grupo',
        ),
    ]
