# Generated by Django 4.0.3 on 2022-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_rename_reino_planta_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='local',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
